# Generated by Django 5.0.1 on 2024-06-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_grades_purchasebooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='student',
            name='region',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
