# Generated by Django 5.0.1 on 2024-06-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_purchasebooks_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
